---
title: "CallsParser"
output:
  html_document:
    df_print: paged
---

# prerequisite

## Packages & function
```{r}
library(ggplot2)

## Calculate belonging section
inSection <- function(time, list) {
  section <- vector(mode="numeric", length = length(time))
  for (i in 1:length(time)) {
    for (j in 1:length(list)) {
      interval <- strsplit(list[j], '~')[[1]]
      if ( (time[i] >= as.numeric(interval[1])) & (time[i] <= as.numeric(interval[2]))) {
        section[i] = list[j]
      }
    }
  }
  return(section)
}



## Parse Data
bindDataFrame <- function(file_list, isInner = TRUE) {
  df <- data.frame()
  
  if (isInner) {
    for (i in file_list) {
      data <- read.csv(i)
      data <- data[,-1]
      df <- rbind(df, data[-1,])
    }
    
    df <- data.frame(time = df[,2], floor = df[,1])
  } else {
    for (i in file_list) {
      data <- read.csv(i)
      data <- data[-c(1:6),]
      data <- data[,c(2:4)]
      data[,4] <- substr(data[,2], 4, 5)
      data[,2] <- substr(data[,2], 1, 2)
      data <- data[-nrow(data),]
      data <- data[-nrow(data),]
      data <- data[-nrow(data),]
      df <- rbind(df, data)
    }
    print(df)
    df <- data.frame(time = df[,1], floor = df[,2], waiting = as.numeric(as.character(df[,3])), direction = df[,4])
  }
  
  rownames(df) <- 1:nrow(df)
  
  df$time <- as.POSIXct(df$time, format="%Y-%m-%d %H:%M:%S")
  df$hour <- as.numeric(format(df$time, format = '%H'))
  df$week <- format(df$time,format = '%w')
  df$section <- as.factor(inSection(df$hour, sections))
  df$type <- as.factor(ifelse(isInner, 'inner', 'outer'))
  df$direction = as.factor(ifelse(substr(df$direction, 1, 2) == "¡¶", "up", "down"))
  return(df)
}
```


## Notes

(第一級)\n
研究大樓: 3021、3022、3023\n
南棟客梯: 3011、3012、3013、3014\n
北棟客梯: 3001、3002、3003、3004\n
南棟病梯床: 3015、3016、3017、3019、3020\n
北棟病梯床: 3006、3007、3008、3009、3010\n

## Dataset

Please Manually modify the following information.

```{r}
# Location name
location <- '研究大樓'

# File names for inner calls
innerFileNames <- c('3011.csv','3022.csv','3023.csv')

# File names for outer calls
outerFileNames <- c('研究大樓.csv','研究大樓1015-1023.csv','研究大樓1024-1031.csv')

# Time interval for each time section
sections <- c('07~10', '11~14', '15~19', '20~23')
```



# Data Processing

## Parse Data Files
```{r}
#inner <- bindDataFrame(innerFileNames, isInner = TRUE)
outer <- bindDataFrame(outerFileNames, isInner = FALSE)

#print(head(inner))
#print(tail(inner))
print(head(outer))
print(tail(outer))
```


```{r}
library(plyr)
outFreq<-count(outer, c("floor", "hour", "week", "direction"))
outTot<-count(outer, c("floor", "hour", "week", "direction"), c("waiting"))
names(outTot)[5]<-'total'
outTot$count<-outFreq$freq
outTot$avgWait<-outTot$total/outFreq$freq
write.csv(outTot, paste("./Waiting/", location,".csv"))
```





